/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.GestionarNavegacion;
import Controlador.SesionGlobal;

/**
 *
 * @author HP
 */
public class ListaFactura extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public ListaFactura() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonFacturaCliente = new javax.swing.JButton();
        buttonFacturaBronce = new javax.swing.JButton();
        buttonFacturaPlata = new javax.swing.JButton();
        buttonFacturaOro = new javax.swing.JButton();
        buttonFacturaDiaria = new javax.swing.JButton();
        buttonFacturaMensual = new javax.swing.JButton();
        buttonFacturaAnual = new javax.swing.JButton();
        buttonFacturaTotal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 241, 186));

        buttonFacturaCliente.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaCliente.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaCliente.setText("Factura de cliente");
        buttonFacturaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturaClienteActionPerformed(evt);
            }
        });

        buttonFacturaBronce.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaBronce.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaBronce.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaBronce.setText("Factura bronce");
        buttonFacturaBronce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaPlata.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaPlata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaPlata.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaPlata.setText("Factura plata");
        buttonFacturaPlata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaOro.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaOro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaOro.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaOro.setText("Factura oro");
        buttonFacturaOro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaDiaria.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaDiaria.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaDiaria.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaDiaria.setText("Factura diaria");
        buttonFacturaDiaria.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaMensual.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaMensual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaMensual.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaMensual.setText("Factura mensual");
        buttonFacturaMensual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaAnual.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaAnual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaAnual.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaAnual.setText("Factura anual");
        buttonFacturaAnual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        buttonFacturaTotal.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaTotal.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaTotal.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaTotal.setText("Factura total");
        buttonFacturaTotal.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturaTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturaTotalActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Listar Facturas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonFacturaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturaBronce, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturaPlata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturaOro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonFacturaAnual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturaMensual, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(buttonFacturaDiaria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturaTotal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturaCliente)
                    .addComponent(buttonFacturaDiaria))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturaBronce)
                    .addComponent(buttonFacturaMensual))
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturaPlata)
                    .addComponent(buttonFacturaAnual))
                .addGap(74, 74, 74)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturaOro)
                    .addComponent(buttonFacturaTotal))
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFacturaTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturaTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonFacturaTotalActionPerformed

    private void buttonFacturaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturaClienteActionPerformed
        if (!SesionGlobal.isLoggedIn()) {
            GestionarNavegacion.setVentanaAnterior(this);
            Login loginWindow = new Login();
            loginWindow.setVisible(true);
            this.setVisible(false);
        } else {
        BusquedaId busquedaId = new BusquedaId();
        busquedaId.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_buttonFacturaClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListaFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFacturaAnual;
    private javax.swing.JButton buttonFacturaBronce;
    private javax.swing.JButton buttonFacturaCliente;
    private javax.swing.JButton buttonFacturaDiaria;
    private javax.swing.JButton buttonFacturaMensual;
    private javax.swing.JButton buttonFacturaOro;
    private javax.swing.JButton buttonFacturaPlata;
    private javax.swing.JButton buttonFacturaTotal;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
