/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import Controlador.GestionarNavegacion;
import Controlador.SesionGlobal;
import Modelo.Facturar;
import javax.swing.JOptionPane;

/**
 *
 * @author HP
 */
public class ListarFactura extends javax.swing.JFrame {

    /**
     * Creates new form Reporte
     */
    public ListarFactura() {
        initComponents();
        this.setDefaultCloseOperation(HIDE_ON_CLOSE);
        this.setLocationRelativeTo(null);
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonFacturaCliente = new javax.swing.JButton();
        buttonFacturasBronce = new javax.swing.JButton();
        buttonFacturasPlata = new javax.swing.JButton();
        buttonFacturasOro = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 241, 186));

        buttonFacturaCliente.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturaCliente.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturaCliente.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturaCliente.setText("Factura de cliente");
        buttonFacturaCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturaCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturaClienteActionPerformed(evt);
            }
        });

        buttonFacturasBronce.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturasBronce.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturasBronce.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturasBronce.setText("Facturas Bronce");
        buttonFacturasBronce.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturasBronce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturasBronceActionPerformed(evt);
            }
        });

        buttonFacturasPlata.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturasPlata.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturasPlata.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturasPlata.setText("Facturas Plata");
        buttonFacturasPlata.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturasPlata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturasPlataActionPerformed(evt);
            }
        });

        buttonFacturasOro.setBackground(new java.awt.Color(51, 51, 51));
        buttonFacturasOro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buttonFacturasOro.setForeground(new java.awt.Color(204, 204, 204));
        buttonFacturasOro.setText("Facturas Oro");
        buttonFacturasOro.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        buttonFacturasOro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFacturasOroActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Listar Facturas");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(280, 280, 280))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(buttonFacturaCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonFacturasPlata, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(109, 109, 109)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(buttonFacturasBronce, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                    .addComponent(buttonFacturasOro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturaCliente)
                    .addComponent(buttonFacturasBronce))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonFacturasPlata)
                    .addComponent(buttonFacturasOro))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFacturaClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturaClienteActionPerformed
        if (!SesionGlobal.isLoggedIn()) {
            GestionarNavegacion.setVentanaAnterior(this);
            Login loginWindow = new Login();
            loginWindow.setVisible(true);
            this.setVisible(false);
        } else {
            String rol = SesionGlobal.getRolUsuario();
            if ("usuario".equals(rol)) {
                String idUsuario = SesionGlobal.getIdUsuario();
                Facturar.generarFacturaPDF(idUsuario);
                JOptionPane.showMessageDialog(this, "Factura generada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            } else if ("administrador".equals(rol)) {
                BusquedaId busquedaId = new BusquedaId();
                busquedaId.setVisible(true);
                this.setVisible(false);
            }
        }
    }//GEN-LAST:event_buttonFacturaClienteActionPerformed

    private void buttonFacturasOroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturasOroActionPerformed
        if (!SesionGlobal.isLoggedIn()) {
            GestionarNavegacion.setVentanaAnterior(this);
            Login loginWindow = new Login();
            loginWindow.setVisible(true);
            this.setVisible(false);
        } else {
            String rol = SesionGlobal.getRolUsuario();
            if ("usuario".equals(rol)) {
                JOptionPane.showMessageDialog(this, "No tienes permisos para ver esta sección.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("administrador".equals(rol)) {
                Facturar.generarFacturaMembresiaPDF("Oro");
                JOptionPane.showMessageDialog(this, "Factura generada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_buttonFacturasOroActionPerformed

    private void buttonFacturasBronceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturasBronceActionPerformed
        if (!SesionGlobal.isLoggedIn()) {
            GestionarNavegacion.setVentanaAnterior(this);
            Login loginWindow = new Login();
            loginWindow.setVisible(true);
            this.setVisible(false);
        } else {
            String rol = SesionGlobal.getRolUsuario();
            if ("usuario".equals(rol)) {
                JOptionPane.showMessageDialog(this, "No tienes permisos para ver esta sección.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("administrador".equals(rol)) {
                Facturar.generarFacturaMembresiaPDF("Bronce");
                JOptionPane.showMessageDialog(this, "Factura generada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_buttonFacturasBronceActionPerformed

    private void buttonFacturasPlataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFacturasPlataActionPerformed
        if (!SesionGlobal.isLoggedIn()) {
            GestionarNavegacion.setVentanaAnterior(this);
            Login loginWindow = new Login();
            loginWindow.setVisible(true);
            this.setVisible(false);
        } else {
            String rol = SesionGlobal.getRolUsuario();
            if ("usuario".equals(rol)) {
                JOptionPane.showMessageDialog(this, "No tienes permisos para ver esta sección.", "Error", JOptionPane.ERROR_MESSAGE);
            } else if ("administrador".equals(rol)) {
                Facturar.generarFacturaMembresiaPDF("Plata");
                JOptionPane.showMessageDialog(this, "Factura generada exitosamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
            }

        }
    }//GEN-LAST:event_buttonFacturasPlataActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarFactura.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListarFactura().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFacturaCliente;
    private javax.swing.JButton buttonFacturasBronce;
    private javax.swing.JButton buttonFacturasOro;
    private javax.swing.JButton buttonFacturasPlata;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
